replicaCount: 1

env: "dev"
version: "1.2"

image:
  name: surveysvc
  tag: migration-sandbox
  repository: eu.gcr.io/rm-ras-sandbox

service:
  port: 8080

resources:
  requests:
    cpu: "500m"
    memory: "256Mi"
  limits:
    cpu: "1000m"
    memory: "512Mi"