sudo: required

services:
  - docker

language: go
go:
 - 1.11

install: true

go_import_path: github.com/ONSdigital/rm-survey-service

script:
  - make build integration-test

after_success:
- if ([ "$TRAVIS_BRANCH" == "rm-census" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]) || ([ "$TRAVIS_BRANCH" == "automate-census-docker-build" ]); then
  docker build -t "$DESTINATION_IMAGE_NAME" .;
  docker login -u "${DOCKER_GCP_USERNAME}" -p "${DOCKER_GCP_PASSWORD}" "${DOCKER_GCP_REGISTRY}";
  docker push "$DESTINATION_IMAGE_NAME";
  fi
- bash <(curl -s https://codecov.io/bash)

env:
  global:
    - DESTINATION_IMAGE_NAME="$DOCKER_GCP_LOCATION/census-rm-surveysvc"

branches:
    only:
        - rm-census