sudo: required

services:
  - docker

language: go
go:
 - 1.11

install: true

go_import_path: github.com/ONSdigital/rm-survey-service

script:
  - docker login -u "${DOCKER_GCP_USERNAME}" -p "${DOCKER_GCP_PASSWORD}" "${DOCKER_GCP_REGISTRY}";
  - make build integration-test

after_success:
- if [ "$TRAVIS_BRANCH" == "rm-census" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  docker build -t "$DESTINATION_IMAGE_NAME" .;
  docker login -u "${DOCKER_GCP_USERNAME}" -p "${DOCKER_GCP_PASSWORD}" "${DOCKER_GCP_REGISTRY}";
  docker push "$DESTINATION_IMAGE_NAME";
  fi
  
- bash <(curl -s https://codecov.io/bash)

env:
  global:
    - DESTINATION_IMAGE_NAME="eu.gcr.io/census-rm-ci/rm/census-rm-surveysvc"

branches:
    only:
        - rm-census
        