sudo: required

services:
  - docker

language: go
go:
 - 1.11

install: true

go_import_path: github.com/ONSdigital/rm-survey-service

script:
  - make build integration-test

after_success:
- if ([ "$TRAVIS_BRANCH" == "rm-census" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]) || ([ "$TRAVIS_BRANCH" == "automate-census-docker-build" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]); then
  docker build -t "${DOCKER_GCP_LOCATION}"/surveysvc .;
  docker login -u "${DOCKER_GCP_USERNAME}" -p "${DOCKER_GCP_PASSWORD}" "${DOCKER_GCP_REGISTRY}";
  docker push "${DOCKER_GCP_LOCATION}"/surveysvc;
  fi
- bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - rm-census
    - automate-census-docker-build
