database:
  container_name: postgres
  image: postgres:9.6-alpine
  ports:
   - "5432:5432"
  environment:
  - POSTGRES_DB=postgres
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=password

survey:
  container_name: surveysvc
  image: sdcplatform/surveysvc
  ports:
   - "8080:8080"
  links:
   - database
  environment:
  - DATABASE_URL=postgres://postgres:password@database/postgres?sslmode=disable
  - security_user_name=admin
  - security_user_password=secret
