swagger: '2.0'
info:
  title: Survey API
  description: Initial API for the Survey microservice.
  version: 10.38.0
schemes:
- http
basePath: /
produces:
- application/json
paths:
  /surveys:
    get:
      summary: List Surveys
      description: Lists all surveys. Surveys are returned in ascending name order.
      parameters:
        - name: Accept
          in: header
          description: Response type, application/json
          required: false
          type: string
      tags:
        - Action
      responses:
        200:
          description: Surveys found
          schema:
            type: array
            items:
              type: string
            example:
              - BRES
        204:
          description: No surveys
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /surveys/{survey}:
    get:
      summary: Get Survey
      description: Gets the specified survey.
      parameters:
        - name: Accept
          in: header
          description: Response type, application/json
          required: false
          type: string
        - in: path
          name: survey
          description: Unique survey name
          required: true
          type: string
      tags:
        - Action
      responses:
        200:
          description: Survey found
          schema:
            $ref: '#/definitions/Survey'
        404:
          description: Survey not found
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Survey:
    type: object
    required:
      - survey
      - classifierTypes
    properties:
      survey:
        description: Unique survey name
        type: string
        example: BRES
      classifierTypes:
        description: Survey classifier types
        type: array
        items:
          type: string
        example:
          - COLLECTION_EXERCISE
          - LEGAL_BASIS
          - RU_REF
          - SIC
  Error:
    type: object
    properties:
      code:
        description: Error code
        type: string
      timestamp:
        description:  Unique error timestamp that can be searched for in logs
        type: integer
      message:
        description: Error message
        type: string
securityDefinitions:
  UserSecurity:
    type: basic
security:
  - UserSecurity: []