apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        appVersion: {{ .Chart.AppVersion }}
        helmVersion: {{ .Chart.Version }}
        env: {{ .Values.env }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "eu.gcr.io/ons-rasrmbs-management/{{ .Chart.Name }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - name: http-server
              containerPort: {{ .Values.containerPort }}
          readinessProbe:
            httpGet:
              path: /info
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 1
            periodSeconds: 20
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /info
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 1
            periodSeconds: 20
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
          env:
          {{- .Values.databaseConfig | nindent 10 -}}
          - name: security_user_name
            valueFrom:
              secretKeyRef:
                name: security-credentials
                key: security-user
          - name: security_user_password
            valueFrom:
              secretKeyRef:
                name: security-credentials
                key: security-password
          - name: ZIPKIN_HOST
            value: "$(ZIPKIN_SERVICE_HOST)"
          - name: ZIPKIN_PORT
            value: "$(ZIPKIN_SERVICE_PORT)"
          - name: ZIPKIN_DSN
            value: "http://$(ZIPKIN_SERVICE_HOST):$(ZIPKIN_SERVICE_PORT)/api/v1/spans"
          - name: ZIPKIN_DISABLE
            value: "false"
          - name: ZIPKIN_SAMPLE_RATE
            value: "1.0"
          - name: DATABASE_URL
            value: "postgres://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=disable"
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
