replicaCount: 1

env: "dev"

image:
  name: survey
  tag: latest
  repository: eu.gcr.io/ons-gcr-rmrasbs

service:
  port: 8080

resources:
  requests:
    cpu: "500m"
    memory: "256Mi"
  limits:
    cpu: "1000m"
    memory: "512Mi"