DROP SCHEMA IF EXISTS survey CASCADE;
DROP ROLE IF EXISTS survey;
CREATE ROLE survey PASSWORD 'survey' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION INHERIT LOGIN;
CREATE SCHEMA survey AUTHORIZATION survey;
REVOKE ALL ON ALL TABLES IN SCHEMA survey FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA survey FROM PUBLIC;
REVOKE CONNECT ON DATABASE postgres FROM PUBLIC;
GRANT CONNECT ON DATABASE postgres TO survey;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA survey TO survey;
GRANT ALL ON ALL SEQUENCES IN SCHEMA survey TO survey;
SET schema 'survey';
CREATE TABLE "survey" (surveyid serial NOT NULL, id uuid NOT NULL, name character varying(20) NOT NULL);
ALTER TABLE "survey" OWNER TO survey;
ALTER TABLE "survey" ADD CONSTRAINT survey_pkey PRIMARY KEY (surveyid);
ALTER TABLE "survey" ADD CONSTRAINT survey_id_key UNIQUE (id);
CREATE TABLE "classifiertypeselector" (classifiertypeselectorid serial NOT NULL, id uuid NOT NULL, surveyid integer NOT NULL, classifiertypeselector character varying(50) NOT NULL);
ALTER TABLE "classifiertypeselector" OWNER TO survey;
ALTER TABLE "classifiertypeselector" ADD CONSTRAINT classifiertypeselector_pkey PRIMARY KEY (classifiertypeselectorid);
ALTER TABLE "classifiertypeselector" ADD CONSTRAINT classifiertypeselector_id_key UNIQUE (id);
ALTER TABLE "classifiertypeselector" ADD CONSTRAINT surveyid_fkey FOREIGN KEY (surveyid) REFERENCES survey(surveyid);
CREATE TABLE "classifiertype" (classifiertypeid serial NOT NULL, classifiertypeselectorid integer NOT NULL, classifiertype character varying(50) NOT NULL);
ALTER TABLE "classifiertype" OWNER TO survey;
ALTER TABLE "classifiertype" ADD CONSTRAINT classifiertype_pkey PRIMARY KEY (classifiertypeid);
ALTER TABLE "classifiertype" ADD CONSTRAINT classifiertypeselectorid_fkey FOREIGN KEY (classifiertypeselectorid) REFERENCES classifiertypeselector(classifiertypeselectorid);
INSERT INTO survey(surveyid, id, name) VALUES (1, 'cb0711c3-0ac8-41d3-ae0e-567e5ea1ef87', 'BRES');
INSERT INTO classifiertypeselector(classifiertypeselectorid, id, surveyid, classifiertypeselector) VALUES (1, 'efa868fb-fb80-44c7-9f33-d6800a17c4da', 1, 'COLLECTION_INSTRUMENT');
INSERT INTO classifiertypeselector(classifiertypeselectorid, id, surveyid, classifiertypeselector) VALUES (2, 'e119ffd6-6fc1-426c-ae81-67a96f9a71ba', 1, 'COMMUNICATION_TEMPLATE');
INSERT INTO classifiertype(classifiertypeid, classifiertypeselectorid, classifiertype) VALUES (1, 1, 'COLLECTION_EXERCISE');
INSERT INTO classifiertype(classifiertypeid, classifiertypeselectorid, classifiertype) VALUES (2, 1, 'RU_REF');
INSERT INTO classifiertype(classifiertypeid, classifiertypeselectorid, classifiertype) VALUES (3, 2, 'LEGAL_BASIS');