DROP SCHEMA IF EXISTS survey CASCADE;
DROP ROLE IF EXISTS survey;

CREATE ROLE survey PASSWORD 'survey'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION INHERIT LOGIN;

CREATE SCHEMA survey AUTHORIZATION survey;

REVOKE ALL ON ALL TABLES IN SCHEMA survey FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA survey FROM PUBLIC;
REVOKE CONNECT ON DATABASE postgres FROM PUBLIC;

GRANT CONNECT ON DATABASE postgres TO survey;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA survey TO survey;
GRANT ALL ON ALL SEQUENCES IN SCHEMA survey TO survey;