name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
  IMAGE: survey
  REGISTRY_HOSTNAME: eu.gcr.io
  HOST: ${{ secrets.GOOGLE_PROJECT_ID }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run Tests
      run: |
        make test
        make integration-test
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GCR_KEY }}
      # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        gcloud auth configure-docker

  # Build the Docker image
    - name: Build Docker Image
      run: |
        docker build -t "$REGISTRY_HOSTNAME"/"$HOST"/"$IMAGE":latest .

    - name: Publish Docker Image
      run: |
        docker push "$REGISTRY_HOSTNAME"/"$HOST"/"$IMAGE":latest

    - name: Helm Image pull
      if: github.ref == 'refs/heads/master'
      run: |
        docker pull gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/helm:latest

    - name: Package Helm
      if: github.ref == 'refs/heads/master'
      run: |
        helm dep up _infra/helm/sample
        helm package _infra/helm/sample

    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: failure()

    - name: Publish Charts
      if: github.ref == 'refs/heads/master'
      run: |
        gsutil cp survey-*.tgz gs://ras-rm-artifacts/act/
